"use client";

import { useEffect, useState, type ReactNode } from "react";
import { ArrowDownLeft, ArrowUpRight, BarChart3, Bell, Boxes, Building2, ChevronDown, CircleDollarSign, FileText, LayoutDashboard, Menu, Settings2, Truck, X } from "lucide-react";
import styles from "./page.module.css";
import { readBusinessProfile } from "@/lib/business-profile";

export default function Home() {
  const [mobileNavOpen, setMobileNavOpen] = useState(false);
  const [profile, setProfile] = useState({ businessName: "Main workspace", ownerName: "Business owner" });
  const [profileReady, setProfileReady] = useState(false);
  useEffect(() => { const details = readBusinessProfile(); if (details) { setProfile({ businessName: details.businessName || "Main workspace", ownerName: details.ownerName || "Business owner" }); setProfileReady(Boolean(details.businessName && details.ownerName)); } }, []);
  return <div className={styles.appShell}>
    <aside className={`${styles.sidebar} ${mobileNavOpen ? styles.sidebarOpen : ""}`}>
      <div className={styles.brandRow}><div className={styles.brandMark}>S</div><div><strong>ScrapFlow</strong><span>Business desk</span></div><button className={styles.closeNav} onClick={() => setMobileNavOpen(false)} aria-label="Close navigation"><X size={18} /></button></div>
      <div className={styles.workspaceSwitch}><span className={styles.workspaceDot} />{profile.businessName} <ChevronDown size={15} /></div>
      <nav className={styles.nav}><p className={styles.navLabel}>Overview</p><a className={`${styles.navItem} ${styles.navItemActive}`} href="/"><LayoutDashboard size={18} />Dashboard</a><a className={styles.navItem} href="/companies"><Building2 size={18} />Companies<span className={styles.navCount}>0</span></a><a className={styles.navItem} href="/stock"><Boxes size={18} />Scrap stock</a><p className={styles.navLabel}>Daily work</p><a className={styles.navItem} href="/purchases"><ArrowDownLeft size={18} />Buy scrap</a><a className={styles.navItem} href="/sales"><ArrowUpRight size={18} />Sell scrap</a><a className={styles.navItem} href="/payments"><CircleDollarSign size={18} />Payments</a><a className={styles.navItem} href="/udhari"><CircleDollarSign size={18} />Udhari / Outstanding</a><a className={styles.navItem} href="/quick-bill"><CircleDollarSign size={18} />Quick bill</a><p className={styles.navLabel}>Insights</p><a className={styles.navItem} href="/reports"><BarChart3 size={18} />Reports</a><a className={styles.navItem} href="/settings"><Settings2 size={18} />Settings</a></nav>
      <div className={styles.sidebarFooter}><div className={styles.avatar}>{profile.ownerName.slice(0, 2).toUpperCase()}</div><div><strong>{profile.ownerName}</strong><span>Owner</span></div><ChevronDown size={15} /></div>
    </aside>
    {mobileNavOpen && <button className={styles.scrim} onClick={() => setMobileNavOpen(false)} aria-label="Close navigation" />}
    <main className={styles.main} id="dashboard">
      <header className={styles.topbar}><button className={styles.menuButton} onClick={() => setMobileNavOpen(true)} aria-label="Open navigation"><Menu size={20} /></button><div className={styles.breadcrumb}><span>Workspace</span><b>/</b><strong>Dashboard</strong></div><div className={styles.topActions}><button className={styles.iconButton} aria-label="Notifications"><Bell size={19} /><i /></button><div className={styles.datePill}>Tuesday, 09 Sep 2026 <ChevronDown size={15} /></div></div></header>
      <section className={styles.content}><div className={styles.hero}><div><p className={styles.eyebrow}>TUESDAY, 09 SEPTEMBER 2026</p><h1>Welcome, {profile.ownerName}.</h1><p className={styles.heroCopy}>Here&apos;s what&apos;s moving across your scrap business today.</p></div><div className={styles.heroActions}>{!profileReady && <a className={styles.setupHint} href="/settings">Set up business details</a>}<a className={styles.primaryButton} href="/quick-bill"><span>+</span>Quick bill</a></div></div>
        <div className={styles.kpiGrid}><MetricCard label="Total stock" value="0" suffix="MT" trend="No data" trendText="Add scrap stock" icon={<Boxes size={19} />} tone="teal" /><MetricCard label="Purchase amount" value="₹0.00" trend="No data" trendText="No purchases yet" icon={<ArrowDownLeft size={19} />} tone="amber" /><MetricCard label="Sales amount" value="₹0.00" trend="No data" trendText="No sales yet" icon={<ArrowUpRight size={19} />} tone="blue" /><MetricCard label="Net outstanding" value="₹0.00" trend="No data" trendText="No outstanding amount" icon={<CircleDollarSign size={19} />} tone="coral" negative /></div>
        <div className={styles.dashboardGrid}><section className={styles.panel}><div className={styles.panelHeader}><div><h2>Cash position</h2><p>Payables and receivables at a glance</p></div><button className={styles.periodButton}>Last 30 days <ChevronDown size={15} /></button></div><div className={styles.emptyDashboard}>No payments or outstanding balances yet.</div></section><section className={styles.panel} id="stock"><div className={styles.panelHeader}><div><h2>Stock snapshot</h2><p>Current inventory by material</p></div><a className={styles.textLink} href="/stock">Add stock <ArrowUpRight size={15} /></a></div><div className={styles.emptyDashboard}>No scrap stock added yet.</div></section></div>
        <section className={styles.panel} id="companies"><div className={styles.panelHeader}><div><h2>Recent activity</h2><p>Your purchases, sales, and payments will appear here.</p></div><a className={styles.textLink} href="/companies">Add company <ArrowUpRight size={15} /></a></div><div className={styles.emptyDashboard}>No activity yet. Add a company to get started.</div></section>
        <div className={styles.quickActions}><div><p className={styles.eyebrow}>QUICK ACTIONS</p><h2>Keep your desk moving</h2></div><div className={styles.actionButtons}><a href="/quick-bill"><CircleDollarSign size={17} />Quick bill</a><a href="/purchases"><ArrowDownLeft size={17} />Buy scrap</a><a href="/sales"><Truck size={17} />Sell scrap</a><a href="/reports"><FileText size={17} />Reports</a></div></div>
      </section>
    </main>
  </div>;
}

function MetricCard({ label, value, suffix, trend, trendText, icon, tone, negative = false }: { label: string; value: string; suffix?: string; trend: string; trendText: string; icon: ReactNode; tone: string; negative?: boolean }) { return <article className={styles.metricCard}><div className={styles.metricTop}><span>{label}</span><div className={`${styles.metricIcon} ${styles[tone]}`}>{icon}</div></div><div className={styles.metricValue}>{value}{suffix && <small>{suffix}</small>}</div><div className={`${styles.trend} ${negative ? styles.trendGood : ""}`}><span>{trend}</span> {trendText}</div></article>; }
function BalanceRow({ label, detail, amount, percentage, tone }: { label: string; detail: string; amount: string; percentage: string; tone: string }) { return <div className={styles.balanceRow}><div className={styles.balanceLabel}><span className={`${styles.balanceIcon} ${styles[tone]}`}>{tone === "receive" ? <ArrowDownLeft size={16} /> : <ArrowUpRight size={16} />}</span><div><strong>{label}</strong><small>{detail}</small></div></div><strong>{amount}</strong><div className={styles.balanceBar}><span className={styles[tone]} style={{ width: percentage }} /></div></div>; }
function StockRow({ name, value, percent, color }: { name: string; value: string; percent: string; color: string }) { return <div className={styles.stockRow}><div className={styles.stockName}><i className={`${styles.stockDot} ${styles[color]}`} /><strong>{name}</strong></div><strong>{value}</strong><div className={styles.stockBar}><span className={styles[color]} style={{ width: percent }} /></div></div>; }
function ActivityRow({ icon, iconTone, type, company, date, amount, status }: { icon: ReactNode; iconTone: string; type: string; company: string; date: string; amount: string; status: string }) { return <tr><td><span className={`${styles.activityIcon} ${styles[iconTone]}`}>{icon}</span><strong>{type}</strong></td><td>{company}</td><td className={styles.muted}>{date}</td><td><strong>{amount}</strong></td><td><span className={`${styles.status} ${styles[status === "Completed" ? "complete" : status === "Payable" ? "payable" : "partial"]}`}>{status}</span></td></tr>; }
